SOURCES     := main.cpp PhoneBook.cpp Contact.cpp

OBJECTS     := $(SOURCES:.cpp=.o)

NAME        := PhoneBook

all: $(NAME)

$(NAME): $(OBJECTS)
	c++ -o $(NAME) $(OBJECTS)

%.o: %.cpp
	c++ -Wall -Werror -Wextra -std=c++98 -c $(SOURCES)

clean:
	rm -rf $(OBJECTS)

fclean: clean
	rm -rf $(NAME)

re: fclean all